# -*- coding: utf-8 -*-
"""OwenLuciano_TugasAkhirSUBA_DSforBeginnersipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u6kPilz9vSNu3ot3yaf1m1SBpaLSuomz

# **Latar Belakang**

Prestasi belajar siswa merupakan indikator penting dalam menilai keberhasilan proses pendidikan. Namun, hasil akademik siswa tidak hanya dipengaruhi oleh kemampuan intelektual, tetapi juga oleh berbagai faktor sosial, ekonomi, dan lingkungan. Oleh karena itu, diperlukan analisis berbasis data untuk memahami faktor-faktor yang memengaruhi performa akademik siswa secara lebih komprehensif.

Dataset Student Performance dari UCI Machine Learning Repository menyediakan data nilai akademik siswa serta berbagai atribut pendukung seperti latar belakang keluarga, kebiasaan belajar, dan kondisi sosial. Dengan memanfaatkan dataset ini, proyek ini bertujuan untuk menganalisis hubungan antara faktor-faktor tersebut terhadap prestasi siswa serta membangun model prediksi nilai akhir. Hasil analisis diharapkan dapat membantu pendidik dalam mengambil keputusan yang lebih tepat guna meningkatkan kualitas pembelajaran.

source : https://archive.ics.uci.edu/dataset/320/student+performance

# **Import Library yang Digunakan**
"""

from google.colab import drive
drive.mount('/content/drive')

import warnings
warnings.filterwarnings('ignore')

# Import library yang digunakan
import pandas as pd

# Eksekusi sintaks berikut untuk meng-custom tampilan
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.float_format', '{:.2f}'.format)

"""# **Ekstraksi Data**"""

# Proses Ekstraksi Data
url = "/content/drive/MyDrive/Colab Notebooks/OwenLuciano_TugasAkhirSUBA_DSforBeginners/StudentMentalHealth_dirty.csv"
data_student = pd.read_csv(url)
# Tampilkan datanya
display(data_student)

"""# **Data Dictionary**

<table border="1" cellspacing="0" cellpadding="4">
  <tr>
    <th>Kolom</th>
    <th>Deskripsi</th>
  </tr>

  <tr>
    <td>Name</td>
    <td>Nama mahasiswa/responden.</td>
  </tr>

  <tr>
    <td>Gender</td>
    <td>Jenis kelamin responden.</td>
  </tr>

  <tr>
    <td>Age</td>
    <td>Usia responden dalam tahun.</td>
  </tr>

  <tr>
    <td>Education Level</td>
    <td>Tingkat pendidikan yang sedang ditempuh.</td>
  </tr>

  <tr>
    <td>Screen Time (hrs/day)</td>
    <td>Durasi penggunaan layar per hari dalam jam.</td>
  </tr>

  <tr>
    <td>Sleep Duration (hrs)</td>
    <td>Rata-rata durasi tidur per hari dalam jam.</td>
  </tr>

  <tr>
    <td>Physical Activity (hrs/week)</td>
    <td>Total durasi aktivitas fisik per minggu dalam jam.</td>
  </tr>

  <tr>
    <td>Stress Level</td>
    <td>Tingkat stres (biasanya skala 1–10).</td>
  </tr>

  <tr>
    <td>Anxious Before Exams</td>
    <td>Indikasi apakah responden merasa cemas sebelum ujian (Yes/No).</td>
  </tr>

  <tr>
    <td>Academic Performance Change</td>
    <td>Perubahan performa akademik</td>
  </tr>
</table>

# **Informasi Umum pada Data**
"""

# Periksa informasi umum pada data
data_student.info()

"""# **Analisa Univariate**

## ***Kolom Kategorik***
"""

# Seleksi kolom dengan tipe object
kolom_kategorik = data_student.select_dtypes(include=['object']).columns

# Tampilkan frekuensinya
for col in kolom_kategorik:
    print(f'> Frekuensi \033[93m{col}\033[0m')
    print(f'  Terdapat {data_student[col].nunique(dropna = False)} data unik\n')
    display(data_student[col].value_counts(dropna = False).reset_index())
    print('\n')

"""Ditemukan karakter pada kolom numerik .... sehingga perlu dilakukan ...

"""

# Ubah string 'twenty' menjadi numerik pada kolom Age
data_student['Age'] = data_student['Age'].str.replace('twenty', '20')

# Konversi tipe datanya
data_student['Age'] = data_student['Age'].astype(pd.Float64Dtype())

import numpy as np

# Ubah string 'unknown' dan string kosong '' pada kolom Screen Time (hrs/day) menjadi None (kosong)
data_student['Screen Time (hrs/day)'] = data_student['Screen Time (hrs/day)'].replace(['unknown', ''], np.nan)

# Konversi tipe datanya
data_student['Screen Time (hrs/day)'] = data_student['Screen Time (hrs/day)'].astype(pd.Float64Dtype())

"""## ***Kolom Numerik***"""

# Seleksi kolom dengan tipe numerik
kolom_numerik = data_student.select_dtypes(include=['float64']).columns

# Task C2 - Statistik Deskriptif Numerik
display(data_student[kolom_numerik].describe())

"""## **Missing Value**

### **Hitung Banyaknya *Missing Value***
"""

# Tampilkan missing value pada data
display(data_student.isna().sum())

"""### **Handling Missing Value - Tipe Kategorik**"""

# Tampilkan ukuran awal
data_student.shape

# Hapus baris yang Academic Performance Change kosong
data_student = data_student.dropna(subset = ['Academic Performance Change'])
data_student.shape

# Isi gender yang kosong dengan 'Other'
data_student['Gender'] = data_student['Gender'].fillna('Other')

# Isi Education Level, Stress Level dan Anxious Before Exams yang kosong dengan 'Unknown'
data_student['Education Level'] = data_student['Education Level'].fillna('Unknown')
data_student['Stress Level'] = data_student['Stress Level'].fillna('Unknown')
data_student['Anxious Before Exams'] = data_student['Anxious Before Exams'].fillna('Unknown')

"""### **Handling Missing Value - Tipe Numerik**"""

# Isikan setiap missing value pada kolom numerik dengan median datanya
for col in kolom_numerik:
    median_data = data_student[col].median()
    data_student[col] = data_student[col].fillna(median_data)

"""### **Periksa Kembali**"""

# Periksa missing value
display(data_student.isnull().sum())

"""## **Duplicated Data**

### **Hitung Banyaknya *Duplikasi Data***
"""

print(f'Jumlah data saat ini : {data_student.shape}')
print(f'Jumlah data duplikat : {data_student.duplicated(keep = False).sum()}')

"""### **Hapus Duplikasi Data**"""

# Hapus duplikasi data
data_student = data_student.drop_duplicates()
print(f'Jumlah data saat ini : {data_student.shape}')

"""## **Outlier**

### **Gunakan Boxplot untuk mendeteksi *Outlier***
"""

import plotly.express as px

def box_plot(series, column_name, color):
    # Buat horizontal box plot
    fig = px.box(
        series,
        orientation = 'h',
        color_discrete_sequence  = [color]
    )

    # Update layout and display the plot
    fig.update_layout(
        title = f'<b>Box Plot {column_name}</b>',
        yaxis = dict(
            title = '',
            showgrid = False,
            showline = False,
            showticklabels = False,
            zeroline = False,
        ),
        xaxis = dict(
            title = column_name,
            showgrid = False,
            showline = True,
            showticklabels = True,
            zeroline = False,
        )
    )

    fig.show()

for col in kolom_numerik:
    box_plot(data_student[col], col, '#B07AA1')

"""### **Gunakan Teknik Winsorizing untuk mengatasi Outlier**"""

# Fungsi untuk teknik winsorizing
def teknik_winsorizing(series):
    # Hitung Q1, Q3, dan IQR
    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)
    IQR = Q3 - Q1

    # Hitung lower dan upper bound
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Jika lower bound negatif maka ubah menjadi 0
    if(lower_bound < 0):
      lower_bound = 0

    # Winsorizing: clip nilai ke batas bawah & atas
    series = series.astype(pd.Float64Dtype())
    winsorized_series = series.clip(lower=lower_bound, upper=upper_bound)

    return (winsorized_series)

for col in kolom_numerik:
    data_student[col] = teknik_winsorizing(data_student[col])
    box_plot(data_student[col], col, '#B07AA1')

"""## **Distribusi**"""

# Your Code
import plotly.express as px

for col in kolom_numerik:
    fig = px.histogram(
        data_student,
        x = col,
        nbins = 25,
        color_discrete_sequence = ['#B07AA1'],
        marginal = "box",
        hover_data = data_student.columns
    )

    fig.update_yaxes(
        showgrid = False,
        showticklabels=False,
        title =''
    )

    fig.update_layout(
        title={
            'text' : f'Distribusi <b><span style="color:#B07AA1"></span> {col}</b>',
            'y':0.92,
            'x':0.5,
            'xanchor': 'center',
            'yanchor': 'top'
        },
        plot_bgcolor = 'rgba(0,0,0,0)',
        bargap = 0.01,
        title_font = dict(size = 25)
    )

    fig.show()

"""# **Analisa Multivariate**

## **Korelasi**
"""

# Task D1 - Hitung korelasi
data_corr = data_student[kolom_numerik].corr()

# Tampilkan hasilnya
display(data_corr)

import plotly.express as px

# Buat Grafiknya
fig = px.imshow(
    data_corr,
    color_continuous_scale='blues',
    title = '<b>Korelasi Kolom Numerik Data Student</b><br>',
    text_auto = True
)

#Menyembunyikan skala/rentang korelasi
fig.update_coloraxes(showscale=False)

#Atur judul heatmap
fig.update_layout(
    title = dict(
        x=0.5,
        y=0.9,
        xanchor='center',
        yanchor='top'
    ),
    width = 1000,
    height = 800
)

#Menampilkan heatmap
fig.show()

"""# **Statistik tiap Kategori Academic Performance Change**"""

data_student.groupby(['Academic Performance Change']).agg(
    total_data = ('Name', 'count'),
    min_age = ('Age', 'min'),
    median_age = ('Age', 'median'),
    max_age = ('Age', 'max'),
    min_screen_time = ('Screen Time (hrs/day)', 'min'),
    median_screen_time = ('Screen Time (hrs/day)', 'median'),
    max_screen_time = ('Screen Time (hrs/day)', 'max'),
    min_sleep_duration = ('Sleep Duration (hrs)', 'min'),
    median_sleep_duration = ('Sleep Duration (hrs)', 'median'),
    max_sleep_duration = ('Sleep Duration (hrs)', 'max')
)

"""# **Data Preprocessing**

## **Feature Selection**
"""

# Copy DataFrame
data_preprocessing = data_student.copy()

# Hapus kolom name
data_preprocessing = data_preprocessing.drop(columns = ['Name'])

# Tampilkan hasilnya
data_preprocessing.head()

"""## **Encoding**"""

# Definisikan ulang kolom kategorik dan kolom numerik
kolom_kategorik = data_preprocessing.select_dtypes(include=['object']).columns
kolom_numerik = data_preprocessing.select_dtypes(include=['number']).columns

# Import library yang dibutuhkan
from sklearn.preprocessing import OrdinalEncoder

# Panggil object Ordinal Encoder
ord_enc = OrdinalEncoder()

# Terapkan
data_preprocessing[kolom_kategorik] = ord_enc.fit_transform(data_preprocessing[kolom_kategorik])

# Tampilkan hasilnya
display(data_preprocessing)

for col, categories in zip(kolom_kategorik, ord_enc.categories_):
    print(f"Mapping untuk \033[93m{col}\033[0m:\n")
    for i, cat in enumerate(categories):
        print(f"  {cat} → {i}")
    print()

"""## **Splitting Data**"""

# Import library yang digunakan
from sklearn.model_selection import train_test_split

# Variabel X untuk fitur dan variabel y untuk target
X = data_preprocessing.drop(columns = ['Academic Performance Change'])
y = data_preprocessing['Academic Performance Change']

# Proses splitting data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size = 0.25,
    random_state = 1
)

# Tampilkan frekuensi kemunculan target
display(y.value_counts())

"""* Declined → 0
* Improved → 1
* Same → 2

## **Imbalance Target**
"""

# Import library imblearn
from imblearn.over_sampling import SMOTE

# Buat object SMOTE
smote = SMOTE()

# Terapkan pada X_train dan X_test dan buat variabel baru hasil oversampling
X_train_resample, y_train_resample = smote.fit_resample(X_train, y_train)

# Tampilkan frekuensi kemunculan target
display(y_train_resample.value_counts())

"""# **Modelling**"""

from imblearn.pipeline import Pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

pipeline = Pipeline(steps=[
    ('scaler', RobustScaler()),
    ('smote', SMOTE()),
    ('model',DecisionTreeClassifier())
])

param_grid = {
    'smote__k_neighbors': [3, 5, 7],
    'model__criterion': ['gini', 'entropy', 'log_loss'],
    'model__max_depth': [None, 5, 10, 20, 30],
    'model__min_samples_split': [2, 5, 10],
    'model__min_samples_leaf': [1, 2, 5],
    'model__class_weight': [None, 'balanced']
}

grid = GridSearchCV(
    estimator = pipeline,
    param_grid = param_grid,
    cv = 5,
    scoring = 'f1_macro',
    n_jobs = -1
)

grid.fit(X_train, y_train)

print("Best Params:", grid.best_params_)
print("Best CV Score:", grid.best_score_)

# Import library yang dibutuhkan
from sklearn.model_selection import StratifiedKFold, cross_val_score

# Masukan parameter yang telah di-tuning
model_dtc = DecisionTreeClassifier(
    criterion = 'entropy',
    max_depth = 30,
    min_samples_leaf = 1,
    min_samples_split = 5,
    splitter = 'best'
)

# Definsikan pipeline baru
new_pipe = Pipeline([
    ('scaler', RobustScaler()),
    ('smote', SMOTE()),
    ('model', model_dtc)
])

# Terapkan pada CV
cv = StratifiedKFold(
    n_splits = 5,
    shuffle = True,
    random_state = 42
)

scores = cross_val_score(new_pipe, X, y, cv=cv, scoring = 'accuracy')

print(f'Scores : {scores}')
print(f'Mean   : {scores.mean()}')
print(f'Std    : {scores.std()}')

model_dtc.fit(X_train_resample, y_train_resample)

# Predict test set labels
y_pred = model_dtc.predict(X_test)

from sklearn import metrics

# Menghitung dan mencetak laporan klasifikasi
classification_report = metrics.classification_report(y_pred, y_test)

# Tampilkan hasilnya
print(classification_report)

import plotly.express as px
from sklearn.metrics import confusion_matrix

# Plot dengan Plotly
fig = px.imshow(
    confusion_matrix(y_test, y_pred),
    text_auto = True,
    color_continuous_scale = 'Blues',
    title = "<b>Confusion Matrix Model Decision Tree</b>",
)

# Ubah tampilan xticks dan yticks
fig.update_xaxes(
    tickmode = "array",
    tickvals = [0, 1, 2],
    ticktext = ['Declined', 'Improved', 'Same']
)

fig.update_yaxes(
    tickmode = "array",
    tickvals = [0, 1, 2],
    ticktext = ['Declined', 'Improved', 'Same'],
    tickangle = -90
)

# Hapus legend / colorbar
fig.update_layout(coloraxis_showscale = False)

# Judul dan label + ukuran figure
fig.update_layout(
    title = dict(
        x = 0.5,
        y = 0.9,
        xanchor = 'center',
        yanchor = 'top'
    ),
    xaxis_title = "<b>Prediksi</b>",
    yaxis_title = "<b>Nilai Sebenarnya</b>",
    width = 700,
    height = 700
)

# Tampilkan grafik
fig.show()